version: "3.7"

services:
    app:
        image: mileschou/lapis:latest
        command:  sh -c "apt-get update && apt-get install -y luarocks; luarocks install lua-resty-mysql; lapis server; tail -f /dev/null"
        ports:
            - 80:80
            - 8080:8080
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - mysqldb:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop

volumes:
    mysqldb: