version: "3.7"

services:
    app:
        image: mileschou/lapis:latest
        command:  sh -c "lapis server && tail -f /dev/null"
        ports:
            - 80:80
            - 8080:8080
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app